name: MLOps Automated Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Docker Container Build
      run: docker build -t test-image:latest .